name: odoo_apexive
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  collection: ^1.18.0
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_easyloading: ^3.0.5
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  get_it: ^7.6.7
  go_router: ^13.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: any
  meta: any

dev_dependencies:
  build_runner: ^2.4.8
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  solid_lints: ^0.1.3

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/

flutter_gen:
  output: lib/core/gen/
  line_length: 80
  integrations:
    flutter_svg: true
    rive: false
    flare_flutter: false
    lottie: false

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: assets/time.png
  background_color: "#0C1D4D"

flutter_native_splash:
  color: "#0C1D4D"
  fullscreen: true
